version: 0.0
os: linux
files:
  - source: devevents-backend.jar
    destination: /webapps/
hooks:
  AfterInstall:
    - location: install_service.sh
      timeout: 180
  ApplicationStop:
    - location: stop_service.sh
      timeout: 180
  ApplicationStart:
    - location: start_service.sh
      timeout: 180
  ValidateService:
    - location: validate_service.sh
      timeout: 300
      