version: 0.0
os: linux
files:
  - source: devevents-backend.jar
    destination: /webapps/
hooks:
  AfterInstall:
    - location: install_service.sh
      timeout: 180
  ApplicationStart:
    - location: start_service.sh
      timeout: 3600
      