language: java
dist: trusty
jdk:
- openjdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
- directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script: "./gradlew distZip"
env:
  global:
    - secure: "AjIEc+kEr3ZicMvfK7irsEYH1FUjgR3/PjIKvky60HuhIsmDLrCBzacqIQAPfatNQjA/f7xO0YI8y/MK5fSn5nwWMll3PEWT/QuIK9mZVleTPjwYfcmb0bEPjzyXNG8vPspV18JmYDUxlPIxLXwHXyIdnUx5kI036TwkiXPeQiSFYGmgmA4bWppJFs4Ru1re+A+80bOatzany4TqeTVxy6H0BhOo6r6hlp3QoY7g6gB+pt4AFvmiD+00DO2JdHwKObS8rldag9Qsnc7Ov1BJAPd6rVhmEhSHgtRZ6kGWvsI11oj7uuis/XwUMnjm/OTtyz7tnL6Ert1ARRnibJCCKcsE943sDdgeHTZJ7+pJq6mCgj012cllIBw4hKUVXLB+Tqft9A0S4DLcXu5Ec4Xx2Dj4y2qs/xGz25PV1+FkSKgNlGWhEkudhRLIvek9DfnfN4wo+OqL/OkTBkhs7Knn4fTnCFqSFMOzxOfuPwDOCj/AEmpAOmv+8A3h53jlQrgr9NY1UclIteWgEPFArY+X1nDUGf2a6w7eLU/IENBGl9ETkyQi2ZR+HCZdj4IV+k6CNJRVg2TNJWd75jcaD7nZ+l1c1C/J5O0fE0TbS5jDWgU74SN36CLfqDrVL/tbnSpUT79UjsLJzL3nYJZSQVXF43f2hXn+FwqCz8Nt+PlJN6E="
deploy:
- provider: s3
  skip_cleanup: true
  local_dir: build/distributions
  bucket: dev-events-code
  upload_dir: backend-builds
  acl: private
  on:
    repo: devchampions/devevents-backend
    branch: master
- provider: codedeploy
  bucket: dev-events-code
  key: backend-builds/devevents-backend.zip
  application: dev_events_backend
  deployment_group: dev_events_deployment_group
  wait-until-deployed: true
notifications:
  slack:
    secure: fKgiQeyU2MkzN9bKO15jElcSnDIJoCEFfkjA8j6RMR4Ycarz7Qg4I2pOKrSrOw/jIim9XiNA7dea1k5eu7tbtpQXwH8CSpW+4sjmstPqNRyJykiIQtbSb00sVx7GZzeCWP456PrMEds9Yr1GhC8GNqe91Vi5J2BDuXIJ0qox7vkVsULFqBTjLogIPIOeROssqxbWjD+H7Tw2kIW3xQlD/NSB+kU/otBbAfzrDpBB0OGs2IjUjwEdjCcKoqut8+zcLRK09kw/cidqXiRHFCvSq4BDXeDz4OfCDaldP9hrpyoWWJmEzJ4WSOJ75qcit4aSFvRlSmnmzHarXq7ks3k4x24jY3FchX3VF1lhQt7+1ux5Sdd5Zhs3WHLoVJ6fd4q5v3Kj3jE/MG4ZI/fmRUPbsfW4ThNQxgCE2PoB0Sj9PCLdpEXAbcUgtp3FT/xFq3wEswqwxtQLg3O1C0bwNohrszd/cbs0PncLdyYCCuMxHFSgIJwfMTB4JOIWCrr8r9HCi1epV9OUZ2yEKs9jtFjRIShy873243Kl8Z/Isr38O9yWgHKkXWyvx+vz6IMMUrggPLrAaP40Zyf7jPgAEII1G/Cp3/H3NS5BhzfTA4C/bL/pFiX4FQz3LvbMrwTeZLLpMUzmU1z5BPpf9ItMycL/pgFZE6IQ9nbnuj8uHVOjYwQ=
